name: Compile Project

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio 2019
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 2019

    - name: Download and install Qt
      run: |
        # Download Qt Installer
        curl -LO https://download.qt.io/official_releases/qt/5.15/5.15.2/qt-opensource-windows-x86-5.15.2.exe
        # Install Qt 5.15.2 32-bit
        Start-Process -Wait -FilePath .\qt-opensource-windows-x86-5.15.2.exe -ArgumentList '/S', '-platform', 'minimal'
        # Install Qt 5.15.2 64-bit
        Start-Process -Wait -FilePath .\qt-opensource-windows-x86_64-5.15.2.exe -ArgumentList '/S', '-platform', 'minimal'

    - name: Download and extract Static Qt 5.15.2
      run: |
        # Download Static Qt 5.15.2
        curl -LO https://github.com/martinrotter/qt5-minimalistic-builds/releases/download/5.15.2/qt-5.15.2-static-msvc2019-x86_64.zip
        # Extract Static Qt 5.15.2
        Expand-Archive -Path .\qt-5.15.2-static-msvc2019-x86_64.zip -DestinationPath C:\Qt\5.15.2\qt-5.15.2-static-msvc2019-x86_64

    - name: Set up MSVC
      run: |
        # Set up MSVC for x86
        Write-Host "Setting up MSVC x86..."
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars32.bat"
        qtenv2.bat addQtPath "C:\Qt\5.15.2\msvc2019"
        # Set up MSVC for x64
        Write-Host "Setting up MSVC x64..."
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        qtenv2.bat addQtPath "C:\Qt\5.15.2\msvc2019_64"
        # Set up MSVC for x64_static
        Write-Host "Setting up MSVC x64_static..."
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        qtenv2.bat addQtPath "C:\Qt\5.15.2\qt-5.15.2-static-msvc2019-x86_64"

    - name: Restart MSVC for IntelliSense
      run: |
        # Restart MSVC to repair IntelliSense
        taskkill /IM devenv.exe /F

    - name: Build Project
      run: |
        # Build the project
        MSBuild.exe GH-Injector-GUI.sln /t:Build /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: GH-Injector-GUI/bin/Release/
