name: Build
on:
  push:
    branches: main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Download and Install Qt
      run: |
        Invoke-WebRequest -Uri https://www.qt.io/download-qt-installer -OutFile qt-installer.exe
        Start-Process -FilePath qt-installer.exe -ArgumentList "--script qt-installer-noninteractive.qs" -Wait
    - name: Add Qt to Path
      run: |
        echo "C:\Qt\5.15.2\msvc2019_32\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Qt\5.15.2\msvc2019_64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append