name: Compile GH-Injector-GUI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      run: |
        # Download Qt Installer
        # Modify the URL if a different version is required
        curl -LO "https://download.qt.io/official_releases/qt/5.15/5.15.2/qt-opensource-windows-x86-5.15.2.exe"
        start /wait qt-opensource-windows-x86-5.15.2.exe --script qt-installer-noninteractive.qs --platform minimal

    - name: Set up Qt VS Tools
      run: |
        # Download Qt VS Tools
        # Modify the URL if a different version is required
        curl -LO "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/TheQtCompany.VSTools2022/vsextensions/QtVisualStudioTools2022/2.6.2/vspackage"
        start /wait "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe" /installvstemplates vspackage

    - name: Set up Static Qt
      run: |
        # Download Static Qt 5.15.2
        # Modify the URL if a different version is required
        curl -LO "https://github.com/martinrotter/qt5-minimalistic-builds/releases/download/5.15.2/qt-5.15.2-static-msvc2019-x86_64.zip"
        7z x -o"C:\Qt\5.15.2" qt-5.15.2-static-msvc2019-x86_64.zip

    - name: Set up MSVC
      run: |
        # Add Qt paths to MSVC
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
        qtenv2.bat -qtdir "C:\Qt\5.15.2\msvc2019"
        qtenv2.bat -qtdir "C:\Qt\5.15.2\msvc2019_64"
        qtenv2.bat -qtdir "C:\Qt\5.15.2\qt-5.15.2-static-msvc2019-x86_64"

    - name: Build project
      run: |
        # Modify the build command if necessary
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" GH-Injector-GUI.sln /t:Build /p:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: GH-Injector-GUI-Release
        path: GH-Injector-GUI/bin/Release/
